[package]
name = "mars-core"
version = "1.0.0"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
terra-cosmwasm = "2.2.0"

cw2 = "0.9.0"
cw20 = "0.9.0"
cw20-base = { version = "0.9.0", features = ["library"] }

cosmwasm-std = "0.16.2"

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.23"

astroport = { git = "https://github.com/astroport-fi/astroport-core.git", tag = "v1.0.0" }

[profile.release]
overflow-checks = true
