[package]
name          = "mars-rewards-collector-osmosis"
version       = "2.0.1"
authors       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
keywords      = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
doctest    = false

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library    = []

[dependencies]
cosmwasm-schema             = { workspace = true }
cosmwasm-std                = { workspace = true, features = ["stargate"] }
cw2                         = { workspace = true }
cw-storage-plus             = { workspace = true }
mars-owner                  = { workspace = true }
mars-rewards-collector-base = { workspace = true }
mars-types                  = { workspace = true }

[dev-dependencies]
mars-osmosis = { workspace = true }
mars-owner   = { workspace = true }
mars-testing = { workspace = true }
mars-utils   = { workspace = true }
osmosis-std  = { workspace = true }
serde        = { workspace = true }
